### ISSUE TITLE
Subject gold label.

### ISSUE THREAD

**Issue by miclaraia** [zooniverse/hco-experiments#9]
@dwright04 @marco-willi 

[Relevant line](https://github.com/zooniverse/hco-experiments/blob/7f98c0e8a3d0f4129fc6b60b275ffb43cd40ecd6/swap/swap/agents/subject.py#L14)

The constructor of a Subject currently requires a gold label is passed. How do we handle the subjects that don't have a gold label, and should it be required to pass a gold label in such isntances? Would it be better to 1. have a default value in the constructor for unlabeled subjects or 2. have a separate method to set the gold label.

This is relevant for the test/train split as the gold label is stripped from some subjects, and for the 'real world' once SWAP is applied to nero.

**Comment by marco-willi** [comment]
@Michael: The reason I added it to the constructor is that I needed that information in the agent/subject class to export it for making analyses / figures.

I am not sure what the most elegant way is but I guess a method to set the label is fine. However, when we export the data the non-gold label subjects must also have a gold-label variable with some default/blank value as the export has to be consistent in the returned fields. 

I was also thinking about other information we might want to pass to the subject class, like metadata of a specific subject. The reason would be to have all relevant information in the class which will make it easier to process and analyse whenever we want to split along this properties.

**Comment by miclaraia** [comment]
@marco-willi Ok. So right now we have the gold labels -1 for expert reviewed but unknown, 0 for bogus, and 1 for real. What value should gold_label have if it has no gold label? @dwright04 Do we need to distinguish between the current -1, which were reviewed by experts with no definitive conclusions, and subjects that were never reviewed by experts? If not, then we can reserve -1 to mean no gold label.

I'm not sure, but I can't see a reason why we can't make this simplification. If we do, then we can assign a -1 default value to the gold label in the constructor, which would solve my problem that none of the subject tests currently run, and removes the necessity for providing an explicit gold label on construction.

**Comment by marco-willi** [comment]
@miclaraia Sorry for messing up the subject-tests, I did not think about updating the tests when I made the change.

Regarding the real "-1" labels: if I understood you correctly @dwright04 , those cases might be of special interest because they constitute the difficult cases? However, in SWAP there is probably no difference between blank/-1 labels as both cannot be used to update user probabilities. So it probably comes down, if we want to use the Subject class to store information we want to extract in order to do analyses. This could be convenient to make graphs directly from the SWAP output without having to join/retrieve data from the db. 

Do we know how the raw data from the Zooniverse export looks like if there is no gold label data?
